### ISSUE TITLE
Add Github Actions to check if each website is up

### ISSUE THREAD

**Issue by Jean-BaptisteC** [TeaOwO/Material-You-Apps#51]
To reduce the work to check each website is up, maybe implement a workflow to do wget regularly (maybe each week) on each website?

**Comment by TeaOwO** [comment]
sounds like a good idea, will try!

**Comment by Jean-BaptisteC** [comment]
More information here:
https://stackoverflow.com/questions/40986340/how-to-wget-a-list-of-urls-in-a-text-file

**Comment by TeaOwO** [comment]
so would `wget -i text_file.txt` work?

**Comment by TeaOwO** [comment]
im currently creating a file for wget to test links.

**Comment by TeaOwO** [comment]
first test seems to be going well (will test more before we close this) https://github.com/TeaOwO/Material-You-Apps/actions/runs/6548936012/job/17784741177

**Comment by Jean-BaptisteC** [comment]
Nice works
Two suggestions:
- Latest version of checkout is v4
- Maybe add cron tasks to execute workflow each week -> more information here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule

**Comment by TeaOwO** [comment]
if im correct `cron: '25 4 * * 6'` this is suppost to automate the workflow to 4:25 on friday?

**Comment by TeaOwO** [comment]
Moved this to a pull request, can you review? https://github.com/TeaOwO/Material-You-Apps/pull/55

**Comment by Jean-BaptisteC** [comment]
Nice work
