### ISSUE TITLE
WeatherYou has been removed from Google Play

### ISSUE THREAD

**Issue by Jean-BaptisteC** [TeaOwO/Material-You-Apps#52]
https://play.google.com/store/apps/details?id=com.rodrigmatrix.weatheryou&gl=US return error 404

**Comment by TeaOwO** [comment]
sorry if i can't fix it right now, im currently creating a file for wget to test links.

**Comment by TeaOwO** [comment]
Link seems to be working again! https://play.google.com/store/apps/details?id=com.rodrigmatrix.weatheryou

**Comment by Jean-BaptisteC** [comment]
For you, not for me :)

**Comment by TeaOwO** [comment]
Not for me anymore too. Eh I'll just link to the github page: https://github.com/rodrigmatrix/weather-you
