### ISSUE TITLE
GCamloader Enhanced is not available

### ISSUE THREAD

**Issue by Jean-BaptisteC** [TeaOwO/Material-You-Apps#54]
Error 404 on https://play.google.com/store/apps/details?id=com.gcamloader.enhanced

**Comment by TeaOwO** [comment]
sorry if i can't fix it right now, im currently creating a file for wget to test links.

**Comment by TeaOwO** [comment]
Link works like normal![Screenshot_20231015-174727~2.png](https://github.com/TeaOwO/Material-You-Apps/assets/123305689/e3836ed4-2003-446d-b9a1-957141a7cf7e)

**Comment by Jean-BaptisteC** [comment]
I think app have geographic restrictions in France

**Comment by TeaOwO** [comment]
> I think app have geographic restrictions in France

should i link to an apk instead?
